<?php

use Drupal\security_review\Check;
use Drupal\security_review\CheckResult;
use Drupal\security_review\Checks\BaseUrl;

/**
 * Implements hook_security_review_checks().
 */
function security_review_security_review_checks() {
  return array(
    new BaseUrl()
  );
}

/**
 * Implements hook_security_review_log().
 */
function security_review_security_review_log(Check $check, $message, array $context, $level) {
  Drupal::logger('security_review')->log($level, $message, $context);
}

/**
 * Implements hook_theme().
 */
function security_review_theme($existing, $type, $theme, $path) {
  return array(
    'run_and_review' => array(
      'template' => 'run_and_review',
      'variables' => array(
        'date' => array(),
        'checks' => array()
      )
    ),
    'general_help' => array(
      'template' => 'general_help',
      'variables' => array(
        'paragraphs' => array(),
        'checks' => array()
      )
    )
  );
}

/**
 * Preprocesses variables for template 'run_and_review'.
 */
function template_preprocess_run_and_review(&$variables) {
  $variables['date'] = format_date($variables['date']);
  foreach ($variables['checks'] as &$check) {
    switch ($check['result']) {
      case CheckResult::SKIPPED:
        $check['result_string'] = 'skipped';
        break;
      case CheckResult::SUCCESS:
        $check['result_string'] = 'success';
        break;
      case CheckResult::FAIL:
        $check['result_string'] = 'fail';
        break;
      case CheckResult::WARN:
        $check['result_string'] = 'warning';
        break;
      case CheckResult::INFO:
        $check['result_string'] = 'info';
        break;
    }
  }
}
