<?php

use Drupal\security_review\Check;
use Drupal\security_review\CheckResult;
use Drupal\security_review\Checks\AdminPermissions;
use Drupal\security_review\Checks\BaseUrl;
use Drupal\security_review\Checks\ErrorReporting;
use Drupal\security_review\Checks\ExecutablePhp;
use Drupal\security_review\Checks\FailedLogins;
use Drupal\security_review\Checks\FilePermissions;
use Drupal\security_review\Checks\InputFormats;
use Drupal\security_review\Checks\PrivateFiles;
use Drupal\security_review\Checks\QueryErrors;
use Drupal\security_review\Checks\TemporaryFiles;
use Drupal\security_review\SecurityReview;

/**
 * Implements hook_security_review_checks().
 */
function security_review_security_review_checks() {
  return array(
    new AdminPermissions(),
    new BaseUrl(),
    new ErrorReporting(),
    new ExecutablePhp(),
    new FailedLogins(),
    new FilePermissions(),
    new InputFormats(),
    new PrivateFiles(),
    new QueryErrors(),
    new TemporaryFiles(),
  );
}

/**
 * Implements hook_security_review_log().
 */
function security_review_security_review_log(Check $check, $message, array $context, $level) {
  Drupal::logger('security_review')->log($level, $message, $context);
}

/**
 * Implements hook_modules_uninstalled().
 */
function security_review_modules_uninstalled($modules) {
  // Delete any orphaned check data.
  SecurityReview::cleanStorage();
}

/**
 * Implements hook_theme().
 */
function security_review_theme($existing, $type, $theme, $path) {
  return array(
    'check_evaluation' => array(
      'template' => 'check_evaluation',
      'variables' => array(
        'paragraphs' => array(),
        'items' => array()
      )
    ),
    'check_help' => array(
      'template' => 'check_help',
      'variables' => array(
        'title' => array(),
        'paragraphs' => array()
      )
    ),
    'general_help' => array(
      'template' => 'general_help',
      'variables' => array(
        'paragraphs' => array(),
        'checks' => array()
      )
    ),
    'run_and_review' => array(
      'template' => 'run_and_review',
      'variables' => array(
        'date' => array(),
        'checks' => array()
      )
    ),
  );
}

/**
 * Preprocesses variables for template 'run_and_review'.
 */
function template_preprocess_run_and_review(&$variables) {
  $variables['date'] = format_date($variables['date']);
  foreach ($variables['checks'] as &$check) {
    $check['style'] = '';
    if ($check['skipped']) {
      $check['style'] .= ' skipped';
    }
    switch ($check['result']) {
      case CheckResult::SUCCESS:
        $check['style'] .= ' success';
        break;
      case CheckResult::FAIL:
        $check['style'] .= ' fail';
        break;
      case CheckResult::WARN:
        $check['style'] .= ' warning';
        break;
      case CheckResult::INFO:
        $check['style'] .= ' info';
        break;
    }
  }
}
