<?php

use Drupal\security_review\Checks;
use Drupal\security_review\CheckResult;

/**
 * Implements hook_security_review_checks().
 */
function security_review_security_review_checks(){
  return array(
    Checks\BaseUrl::getInstance(),
  );
}

/**
 * Implements hook_theme().
 */
function security_review_theme($existing, $type, $theme, $path) {
  return array(
    // Template for list of bingo participants.
    'run_and_review' => array(
      'template' => 'run_and_review',
      'variables' => array(
        'date' => array(),
        'checks' => array()
      ),
    ),
  );
}

function template_preprocess_run_and_review(&$variables){
  $variables['date'] = format_date($variables['date']);
  foreach($variables['checks'] as &$check){
    // Determine css styles.
  }
}
